#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    src_dir_node = bld.path.find_dir('../src')
    source = src_dir_node.ant_glob('*/**/*.vala')
    source.append(bld.path.find_or_declare('../data/lottanzb.gresource.c'))
    source.extend(bld.path.ant_glob('**/*.vala'))
    app = bld.program(target='lottanzb-test', features='glib2', source=source,
        vapi_dirs='../vapi',
        cflags=['-g'] + ['-include' + bld.path.find_or_declare(header_file).abspath() \
            for header_file in ['../config.h', '../data/lottanzb.gresource.h']],
        packages='glib-2.0 gio-2.0 gtk+-3.0 gmodule-2.0 json-glib-1.0 ' + \
            'libsoup-2.4 libvala-0.16 gee-1.0 launchpad-integration-3.0 ' + \
            'lottanzb-config lottanzb-resource',
        uselib='GLIB GIO GTK+ GMODULE LIBSOUP JSON VALA GEE LP',
        vala_defines=['DEBUG', 'ENABLE_TEST'],
        install_path=None)
