#!/usr/bin/env python
# encoding: utf-8

from waflib import Options

def build(bld):
    source = bld.path.ant_glob(incl='**/*.vala')
    source.append(bld.path.find_or_declare('lottanzb-test.gresource.c'))
    app = bld.program(
        target='lottanzb-test',
        features='glib2 test',
        source=source,
        vapi_dirs='../vapi ../liblottanzb',
        use='liblottanzb',
        cflags=['-g'] + ['-include' + bld.path.find_or_declare(header_file).abspath() \
            for header_file in ['../config.h', '../data/lottanzb.gresource.h', 'lottanzb-test.gresource.h']],
        packages='glib-2.0 gio-2.0 gtk+-3.0 gmodule-2.0 json-glib-1.0 ' + \
            'libsoup-2.4 gee-1.0 launchpad-integration-3.0 unique-3.0 ' + \
            'lottanzb-config lottanzb-resource lottanzb-test-resource',
        uselib='GLIB GIO GTK+ GMODULE LIBSOUP JSON GEE LP UNIQUE',
        vala_defines=['DEBUG', 'ENABLE_TEST'],
        install_path=None)
    app.add_resource_bundles(['lottanzb-test.gresource.xml'])
