/* Auto-generated by gen-vala-gtk-widget-bindings.xslt */

public abstract class Lottanzb.AbstractDownloadList : Object {

	protected class WindowWidgets : Object {

		public Gtk.UIManager ui_manager { get; set; }
		public Gtk.ActionGroup important_action_group { get; set; }
		public Gtk.Action remove { get; set; }
		public Gtk.ActionGroup action_group { get; set; }
		public Gtk.Action move_down { get; set; }
		public Gtk.Action move_up { get; set; }
		public Gtk.Action move_up_to_top { get; set; }
		public Gtk.Action move_down_to_bottom { get; set; }
		public Gtk.Action show_properties_dialog { get; set; }
		public Gtk.ToggleAction pause { get; set; }
		public Gtk.Action open_folder { get; set; }
		public Gtk.Menu context_menu { get; set; }
		public Gtk.Window window1 { get; set; }
		public Gtk.HBox download_list { get; set; }
		public Gtk.Toolbar reordering_pane { get; set; }
		public Gtk.ScrolledWindow download_list_container { get; set; }
		public Gtk.TreeView treeview { get; set; }
		public Gtk.TreeSelection treeview_selection1 { get; set; }

	}

	protected Gtk.Builder builder;
	protected WindowWidgets widgets;

	construct {
		builder = new Gtk.Builder ();
		try {
			builder.add_from_resource ("/org/lottanzb/gui/" + ui_file_name);
		} catch (Error e) {
			error ("could not load UI file: %s", e.message);
			exit (-1);
		}
		widgets = new WindowWidgets ();
		SList<unowned Object> objects = builder.get_objects ();
		foreach (Object object in objects) {
			if (object is Gtk.Buildable) {
				widgets.set ((object as Gtk.Buildable).get_name (), object);
			}
		}
		builder.connect_signals (this);
	}
	
	private static const string ui_file_name = "download_list.ui";

}
