.TH LOTTANZB 1 "February 2011" "0.6"

.SH NAME
lottanzb - Usenet Downloader

.SH SYNOPSIS
.B lottanzb [options] [files]

.SH DESCRIPTION
.B LottaNZB
aims to simplify and automate the download of files from the Usenet. You can tell LottaNZB what to download using NZB files, which are created by many Usenet search engines. LottaNZB integrates nicely with GNOME desktops, but is not limited to them and uses the mature SABnzbd software as its foundation.

.SH OPTIONS
.TP
.I [files]
List of NZB files to add to the download queue.
.TP
.I --version
Show program's version number and exit.
.TP
.I -h, --help
Show this help message and exit.
.TP
.I -d --debug
Show debug messages.

.SH SEE ALSO
.B Homepage:
http://www.lottanzb.org/

.SH AUTHOR
This manual page was written by Severin Heiniger <severinheiniger@gmail.com> for the Debian system (but may be used by others).

Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
