#!/usr/bin/env python
# encoding: utf-8

from waflib import Utils

def build(bld):
    if bld.cmd == 'install':
        try:
            mime_database_path = Utils.subst_vars('${DATADIR}/mime', bld.env)
            desktop_database_path = Utils.subst_vars('${DATADIR}/applications', bld.env)
            bld.exec_command(['update-mime-database', mime_database_path])
            bld.exec_command(['update-desktop-database', desktop_database_path])
        except:
            pass
    bld(features='intltool_in', podir='../po', flags=['-d', '-q', '-u', '-c'],
        source='lottanzb.desktop.in', target='lottanzb.desktop',
        install_path='${DATADIR}/applications')
    bld(features='intltool_in', podir='../po', flags=['-x', '-q', '-u', '-c'],
        source='mime/lottanzb.xml.in', target='lottanzb.xml',
        install_path='${DATADIR}/mime/packages/')
