/* Auto-generated by gen-vala-gtk-widget-bindings.xslt */

public abstract class Lottanzb.AbstractInfoBar : Object {

	public class WindowWidgets : Object {

		public Gtk.Window window { get; protected set; }
		public Gtk.Alignment info_bar { get; protected set; }
		public Gtk.HBox hbox1 { get; protected set; }
		public Gtk.Label total_remaining { get; protected set; }
		public Gtk.HBox free_space_container { get; protected set; }
		public Gtk.Image free_space_icon { get; protected set; }
		public Gtk.Label free_space { get; protected set; }
		public Gtk.HBox speed_container { get; protected set; }
		public Gtk.Label speed { get; protected set; }

	}

	protected Gtk.Builder builder;
	public WindowWidgets widgets;

	construct {
		builder = new Gtk.Builder ();
		try {
			builder.add_from_resource ("/org/lottanzb/gui/" + ui_file_name);
		} catch (Error e) {
			error ("could not load UI file: %s", e.message);
			exit (-1);
		}
		widgets = new WindowWidgets ();
		SList<unowned Object> objects = builder.get_objects ();
		foreach (Object object in objects) {
			if (object is Gtk.Buildable) {
				widgets.set ((object as Gtk.Buildable).get_name (), object);
			}
		}
		builder.connect_signals (this);
	}
	
	private static const string ui_file_name = "info_bar.ui";

}