#! /usr/bin/env python
# encoding: utf-8

from waflib import Options

def build(bld):
    app = bld.program(
        target='lottanzb',
        features='glib2',
        source='Main.vala',
        vapi_dirs='../vapi ../liblottanzb',
        use='liblottanzb',
        cflags=['-g'] + ['-include' + bld.path.find_or_declare(header_file).abspath() \
                for header_file in ['../config.h', '../data/lottanzb.gresource.h']],
        packages='glib-2.0 gio-2.0 gtk+-3.0 gmodule-2.0 json-glib-1.0 ' + \
            'libsoup-2.4 libvala-0.16 gee-1.0 launchpad-integration-3.0 unique-3.0 ' + \
            'lottanzb-config lottanzb-resource lottanzb-test-resource ' + \
            'lottanzb-gsettings-workaround',
        uselib='GLIB GIO GTK+ GMODULE LIBSOUP JSON VALA GEE LP UNIQUE',
        vala_defines=['DEBUG'])
